version: '3'

services:
  redis:
    build:
      context: backend/smart_sec_cam/redis
    ports:
      - "6379:6379"
      - "6380:6380"
    restart: always
  server:
    build:
      context: backend/
      dockerfile: smart_sec_cam/server/Dockerfile
    command: python smart_sec_cam/server/server.py --redis-url redis
    volumes:
      - ./data/videos/:/backend/data/videos/
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
  motion-detection:
    build:
      context: backend/
      dockerfile: smart_sec_cam/motion/Dockerfile
    command: python smart_sec_cam/motion/main.py --redis-url redis
    volumes:
      - ./data/videos/:/backend/data/videos/
    depends_on:
      - redis
    restart: always
  frontend:
    build:
      context: frontend/smart-sec-cam
    working_dir: /frontend
    ports:
      - "3000:3000"
    restart: always