version: '3'

services:
  redis:
    build:
      context: backend/smart_sec_cam/redis
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/redis:master"
    ports:
      - "6379:6379"
      - "6380:6380"
    restart: always
  server:
    build:
      context: backend/
      dockerfile: smart_sec_cam/server/Dockerfile
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/backend:master"
    command: python smart_sec_cam/server/server.py --redis-url sec-cam-server --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
      - ./certs/sec-cam-server.cert:/backend/certs/fullchain.pem
      - ./certs/sec-cam-server.key:/backend/certs/privkey.pem
    ports:
      - "8444:8444"
    depends_on:
      - redis
    restart: always
  motion-detection:
    build:
      context: backend/
      dockerfile: smart_sec_cam/motion/Dockerfile
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/motion:master"
    command: python smart_sec_cam/motion/main.py --redis-url redis --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
    depends_on:
      - redis
    restart: always
  frontend:
    build:
      context: frontend/smart-sec-cam
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/frontend:master"
    working_dir: /frontend
    ports:
      - "8443:8443"
    volumes:
      - ./frontend/smart-sec-cam/.env:/frontend/.env
      - ./certs/sec-cam-server.cert:/frontend/certs/fullchain.pem
      - ./certs/sec-cam-server.key:/frontend/certs/privkey.pem
    environment:
      - WDS_SOCKET_PORT=8443
    restart: always

