version: '3'

services:
  redis:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/redis:master"
    build:
      context: backend/smart_sec_cam/redis
    ports:
      - "6379:6379"
      - "6380:6380"
    restart: always
  server:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/backend:master"
    build:
      context: backend/
      dockerfile: smart_sec_cam/server/Dockerfile
    command: python smart_sec_cam/server/server.py --redis-url sec-cam-server --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
      - ./certs/:/backend/certs/
    ports:
      - "8444:8444"
    depends_on:
      - redis
    restart: always
  motion-detection:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/motion:master"
    build:
      context: backend/
      dockerfile: smart_sec_cam/motion/Dockerfile
    command: python smart_sec_cam/motion/main.py --redis-url redis --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
    depends_on:
      - redis
    restart: always
  frontend:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/frontend:master"
    build:
      context: frontend/smart-sec-cam
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./certs/:/frontend/certs/
    environment:
      - WDS_SOCKET_PORT=8443
    restart: always

