version: '3'

services:
  redis:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/redis:master"
    build:
      context: backend/smart_sec_cam/redis
    ports:
      - "6379:6379"
      - "6380:6380"
    restart: always
  server:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/backend:master"
    build:
      context: .
      dockerfile: backend/smart_sec_cam/server/Dockerfile
    entrypoint: /backend/smart_sec_cam/server/docker-entrypoint.sh
    volumes:
      - ./data/videos/:/backend/data/videos/
      - ./certs/:/backend/certs/
    environment:
      - API_URL=${API_URL}
    ports:
      - "8443:8443"
    depends_on:
      - redis
    restart: always
  motion-detection:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/motion:master"
    build:
      context: backend/
      dockerfile: smart_sec_cam/motion/Dockerfile
    command: python smart_sec_cam/motion/main.py --redis-url redis --video-dir /backend/data/videos/ --motion-threshold 10000
    volumes:
      - ./data/videos/:/backend/data/videos/
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
