version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  backend:
    build:
      context: backend/
    command: python server.py --redis-url redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
  frontend:
    build:
      context: frontend/smart-sec-cam
    working_dir: /frontend
    ports:
      - "3000:3000"
    restart: always