version: '3'
services:
  redis:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/redis:master"
    ports:
      - "6379:6379"
      - "6380:6380"
    restart: always
  server:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/backend:master"
    command: python smart_sec_cam/server/server.py --redis-url redis --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
      - ./certs/sec-cam-server.cert:/backend/certs/fullchain.pem
      - ./certs/sec-cam-server.key:/backend/certs/privkey.pem
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
  motion-detection:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/motion:master"
    command: python smart_sec_cam/motion/main.py --redis-url redis --video-dir /backend/data/videos/
    volumes:
      - ./data/videos/:/backend/data/videos/
    depends_on:
      - redis
    restart: always
  frontend:
    image: "container-registry:5050/scottgbarnes/smart-sec-cam/frontend:master"
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/smart-sec-cam/.env:/frontend/.env
      - ./certs/sec-cam-server.cert:/frontend/certs/fullchain.pem
      - ./certs/sec-cam-server.key:/frontend/certs/privkey.pem
    restart: always
  nginx-proxy:
    image: nginx:latest
    ports:
      - "8443:8443"
      - "9443:9443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/sec-cam-server.cert:/fullchain.pem
      - ../certs/sec-cam-server.key:/privkey.pem